version: "3.9"

services:

  # Bot API service
  bot-api:
    environment:
      TELEGRAM_WEB_APP_URL: https://${NGROK_DOMAIN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    restart: on-failure
    build:
      context: bot

  # Bot UI in development mode
  bot-ui:
    restart: on-failure
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
    build:
      context: ./frontend
      dockerfile: dev.dockerfile

  postgres-container:
    image: postgres:latest
    restart: no
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend-container:
    env_file:
      - .env
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8888
    ports:
      - "8888:8888"

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    env_file:
      - .env


  # Nginx proxy to forward request to UI and API
  dev-proxy:
    image: nginx:stable-alpine
    environment:
      PORT: 3000
      API_URL: http://bot-api:3000
      UI_URL: http://bot-ui:3000
    restart: on-failure
    volumes:
      - ./proxy.template:/etc/nginx/templates/default.conf.template

  # Ngrok service
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    restart: on-failure
    command: ["http", "--domain=${NGROK_DOMAIN}", "dev-proxy:3000", "--log=stdout"]

volumes:
  postgres-data: