name: AWS-EC2 Instance CD

on:
  workflow_run:
    workflows: ["Frontend CI with Docker"]
    types: [completed]

jobs:
  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: AWS SSM Send-Command
        uses: nekitkas/aws-ssm-send-command@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          # Command execution location
          # !!! The line below may vary depending on where your docker-compose file is located.
          working-directory: /home/ubuntu
          # Bash commands you want to execute
          command: |
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -af
          # Comment for Send-Command
          comment: docker-compose.yml file re-pulls newer versions of book-portal images and runs them on the instance.